# Generated by Django 3.2.2 on 2021-05-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('longitude', models.CharField(max_length=25, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=25, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'Youtube'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('VK', 'Vk')], max_length=10, verbose_name='Имя')),
                ('link', models.CharField(max_length=50, verbose_name='Ссылка')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='contacts.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Соц сеть',
                'verbose_name_plural': 'Соц сети',
            },
        ),
    ]
